services:
  postgres:
    image: postgres:18-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: fleetmanager
      POSTGRES_PASSWORD: fleetmanager
      POSTGRES_DB: fleetmanager
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379

  mosquito:
    image: emqx/emqx:5.7
    ports:
      # Standard MQTT protocol
      - "1883:1883"
      # MQTT over WebSocket
      - "8083:8083"
      # MQTT over WebSocket Secure
      - "8084:8084"
      # MQTT over TLS
      - "8883:8883"
      # Dashboard web UI
      - "18083:18083"
    volumes:
        # Persist EMQX data (retained messages, sessions, etc.)
      - emqx_data:/opt/emqx/data
        # Persist logs
      - emqx_log:/opt/emqx/log
    environment:
        # Set the node name for clustering
      EMQX_NAME: emqx
        # Set the dashboard admin password
      EMQX_DASHBOARD__DEFAULT_PASSWORD: "my_secure_password"
    healthcheck:
      test: [ "CMD", "emqx", "ctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped


volumes:
  postgres_data:
  emqx_data:
  emqx_log: