services:
  postgres:
    image: postgres:18-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: fleetmanager
      POSTGRES_PASSWORD: fleetmanager
      POSTGRES_DB: fleetmanager
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379

volumes:
  postgres_data: